### PR TITLE
add request retrier

### PR DESCRIPTION
**Pull request by chessman**
This change is [Reviewable](https://reviewable.io/reviews/istreamdata/documentdb-go/8)

### CODE REVIEW

**Comment by dennwc** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client.go, line 198 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuW6cfpzv7mtgvuZ2R:-KyuW6cfpzv7mtgvuZ2S:b25f73z) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L198)):*
> ```Go
> 			return nil, err
> 		}
> 		defer resp.Body.Close()
> ```

Resource leak. Defer will be executed after function return, not after current loop iteration.

---

*[client.go, line 205 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuWFMQGSH4OL6RaLv4:-KyuWFMQGSH4OL6RaLv5:baqz3xx) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L205)):*
> ```Go
> 			return nil, ErrPreconditionFailed
> 		}
> 		if resp.StatusCode == 429 || resp.StatusCode == 503 {
> ```

Magic numbers. Change to `http.StatusXxx`.

---

*[client.go, line 210 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuXT_-WPfciGMSP2lV:-KyuXT_-WPfciGMSP2lW:b9789v0) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L210)):*
> ```Go
> 				delay := retryDelay(r.RetryCount)
> 				t := time.NewTimer(delay)
> 				defer t.Stop()
> ```

Defer inside of the loop. Move to `case <-ctx.Done()`.

---

*[client.go, line 215 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuXgNiPAyrp47D8vMb:-KyuXgNiPAyrp47D8vMc:b30hx1t) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L215)):*
> ```Go
> 					return nil, ctx.Err()
> 				case <-t.C:
> 					continue
> ```

Move `continue` outside of select. It gives more visibility that whole `if` branch will always continue the loop.

---

*[client.go, line 231 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuYBjdBg8PBBSJwzVW:-KyuYBjdBg8PBBSJwzVX:b-t7u45y) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L231)):*
> ```Go
> }
> 
> func retryDelay(retryCount int) time.Duration {
> ```

`backoffDelay`

---

*[client.go, line 236 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuY3U1UqwUpTV6XwvJ:-KyuY3U1UqwUpTV6XwvK:b-gbw3el) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L236)):*
> ```Go
> 	if retryCount > 13 {
> 		retryCount = 13
> 	} else if retryCount > 8 {
> ```

Weird condition

---

*[request.go, line 46 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuWQreh1iEtoY55izG:-KyuWQreh1iEtoY55izH:b5mzd7t) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/request.go#L46)):*
> ```Go
> func ResourceRequest(link string, req *http.Request) *Request {
> 	rId, rType := parse(link)
> 	return &Request{rId, rType, req, 0}
> ```

Name fields

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8)*

**Comment by chessman** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client.go, line 236 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuY3U1UqwUpTV6XwvJ:-KyusayuPGBVhW82DIrn:bnvio4l) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L236)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Weird condition
</blockquote></details>

it's from aws sdk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8)*

**Comment by dennwc** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client.go, line 236 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuY3U1UqwUpTV6XwvJ:-KyvEUtvgb_51HR4r9zm:bd1jee8) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L236)):*
<details><summary><i>Previously, chessman (Eugene Apollonsky) wrote…</i></summary><blockquote>

it's from aws sdk
</blockquote></details>

What exactly? `retryCount > 13` and `retryCount > 8`?

---

*[client.go, line 185 at r2](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyvEm3SNPfToUa4-AMj:-KyvEm3SNPfToUa4-AMk:b-cfok6g) ([raw file](https://github.com/istreamdata/documentdb-go/blob/26d9cef6456663bc6b5d63498d474a481e56da98/client.go#L185)):*
> ```Go
> func (c *Client) checkResponse(ctx context.Context, r *Request, resp *http.Response) error {
> 	if retriable(resp.StatusCode) {
> 		r.RetryCount++
> ```

Maybe it should be a local variable, not a struct field?

---

*[client.go, line 233 at r2](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyvDgmirksX3ndjh8k9:-KyvDgmirksX3ndjh8kA:bczsm8o) ([raw file](https://github.com/istreamdata/documentdb-go/blob/26d9cef6456663bc6b5d63498d474a481e56da98/client.go#L233)):*
> ```Go
> 			ResponseHook(ctx, r.Request.Method, resp.Header)
> 		}
> 		if err := c.checkResponse(ctx, r, resp); err == errRetry {
> ```

You may un-inline `c.checkResponse` and place defer directly after `err == errRetry` branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8)*

**Comment by chessman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client.go, line 236 at r1](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-KyuY3U1UqwUpTV6XwvJ:-KyvI7r1xdzYtTUo5hl_:bdtg85n) ([raw file](https://github.com/istreamdata/documentdb-go/blob/ed82c287aae95183efe31ec65501fb739e070bbe/client.go#L236)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

What exactly? `retryCount > 13` and `retryCount > 8`?
</blockquote></details>

8 is ~2 mins. 13 is ~1 hour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8)*

**Comment by dennwc** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/documentdb-go/8#-:-KyvLYcUtD_kHNtcmrOt:bnfp4nl)*

**Pull request merged**
